var states = {
usa: {
    "Alabama": ["GA", "FL", "TN", "MS"],
    "Alaska": [],
    "Arizona": ["CA", "NV", "UT", "CO", "NM"],
    "Arkansas": ["MO", "OK", "TX", "LA", "TN", "MS"],
    "California": ["OR", "NV", "AZ"],
    "Colorado": ["WY", "NE", "KS", "OK", "NM", "AZ", "UT"],
    "Connecticut": ["MA", "NY", "RI"],
    "District of Columbia": ["MD", "VA"],
    "Delaware": ["MD", "PA"],
    "Florida": ["AL", "GA"],
    "Georgia": ["SC", "NC", "TN", "AL", "FL"],
    "Hawaii": [],
    "Idaho": ["WA", "MT", "OR", "WY", "UT", "NV"],
    "Illinois": ["WI", "IA", "MO", "KY", "IN"],
    "Indiana": ["MI", "IL", "KY", "OH"],
    "Iowa": ["MN", "SD", "NE", "MO", "WI", "IL"],
    "Kansas": ["NE", "CO", "OK", "MO"],
    "Kentucky": ["IN", "IL", "MO", "TN", "OH", "WV", "VA"],
    "Louisiana": ["AR", "TX", "MS"],
    "Maine": ["NH"],
    "Maryland": ["PA", "VA", "WV", "DC", "DE"],
    "Massachusetts": ["NH", "NY", "RI", "VT", "CT"],
    "Michigan": ["WI", "IN", "OH"],
    "Minnesota": ["ND", "SD", "IA", "WI"],
    "Mississippi": ["TN", "AR", "LA", "AL"],
    "Missouri": ["IA", "NE", "KS", "OK", "AR", "IL", "KY", "TN"],
    "Montana": ["ID", "WY", "SD", "ND"],
    "Nebraska": ["SD", "WY", "CO", "KS", "MO", "IA"],
    "Nevada": ["OR", "ID", "UT", "AZ", "CA"],
    "New Hampshire": ["VT", "ME", "MA"],
    "New Jersey": ["NY", "PA"],
    "New Mexico": ["AZ", "UT", "CO", "OK", "TX"],
    "New York": ["PA", "NJ", "VT", "MA", "CT"],
    "North Carolina": ["GA", "TN", "SC", "VA"],
    "North Dakota": ["MT", "SD", "MN"],
    "Ohio": ["MI", "IN", "KY", "WV", "PA"],
    "Oklahoma": ["KS", "CO", "NM", "TX", "AR", "MO"],
    "Oregon": ["WA", "ID", "NV", "CA"],
    "Pennsylvania": ["WV", "NY", "NJ", "DE", "MD", "OH"],
    "Rhode Island": ["MA", "CT"],
    "South Carolina": ["GA", "NC"],
    "South Dakoa": ["ND", "MT", "WY", "NE", "MN", "IA"],
    "Tennessee": ["KY", "MO", "AR", "MS", "AL", "GA", "NC", "VA"],
    "Texas": ["OK", "NM", "LA", "AR"],
    "Utah": ["ID", "NV", "WY", "CO", "AZ", "NM"],
    "Vermont": ["MA", "NH", "NY"],
    "Virginia": ["WV", "KY", "NC", "MD", "TN", "DC"],
    "Washington": ["OR", "ID"],
    "West Virginia": ["OH", "VA", "KY", "MD", "PA"],
    "Wisconsin": ["MN", "IA", "IL", "MI"],
    "Wyoming": ["MT", "SD", "NE", "CO", "UT", "ID"]
}
}
